modLoader="javafml" #mandatory
loaderVersion="${forge_range}" #mandatory
license="MIT"
issueTrackerURL="https://github.com/ChiefArug/kindled/issues" #optional
[[mods]] #mandatory
modId="kindled" #mandatory
version="${kindled_version}" #mandatory
displayName="kindled" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/kindled/" #optional
logoFile="pack.png" #optional
logoBlur=false #optional
authors="ChiefArug" #optional
displayTest="MATCH_VERSION"
description='''
Spooky scary stuff
'''
[[dependencies.kindled]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.kindled]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
